name: 'Cashbook (scheduled)'

on:
  push:
    branches:
      - main
# on:
#   schedule:
#     - cron: "30 00 * * *"  # 7:30 AM GMT+7
    
jobs:
  clone-git-then-build-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Try selenium test
        uses: ThangNguyen0495/Customs@s1.0.2
        with:
          test_config: "test_config/web/LoginDashboardVN.xml"
          test_name: "test selenium"
